# Generated by Django 2.2.7 on 2019-12-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statics', '0002_review_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='expression',
            field=models.CharField(choices=[('good', 'Good'), ('soso', 'Soso'), ('sad', 'Sad'), ('surprise', 'Surprise')], max_length=100),
        ),
    ]
