# Generated by Django 2.2.7 on 2019-12-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statics', '0005_noticecheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='expression',
            field=models.CharField(choices=[('good', 'Good'), ('soso', 'Soso'), ('sad', 'Sad'), ('surprise', 'Surprise'), ('thumb', 'Thumb')], max_length=100),
        ),
    ]
