# Generated by Django 2.2.7 on 2019-12-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statics', '0006_auto_20191220_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='replies',
            field=models.ManyToManyField(blank=True, null=True, related_name='_reply_replies_+', to='statics.Reply'),
        ),
    ]
