# Generated by Django 2.2.7 on 2019-12-26 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statics', '0007_reply_replies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='replies',
            field=models.ManyToManyField(blank=True, related_name='_reply_replies_+', to='statics.Reply'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('comment_review', 'Comment Review'), ('comment_reply', 'Comment Reply'), ('like_review', 'Like Review')], max_length=255, verbose_name='알림 유형')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_notifications', to=settings.AUTH_USER_MODEL)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='statics.Reply')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='statics.Review')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림',
                'ordering': ['-id'],
            },
        ),
    ]
