# Generated by Django 2.2.7 on 2019-12-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statics', '0008_auto_20191226_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('comment_review', 'Comment Review'), ('comment_reply', 'Comment Reply'), ('like_review', 'Like Review'), ('following', 'Following')], max_length=255, verbose_name='알림 유형'),
        ),
    ]
