# Generated by Django 2.2.7 on 2019-12-26 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statics', '0009_auto_20191226_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='statics.Reply'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='statics.Review'),
        ),
    ]
