# Generated by Django 2.2.7 on 2019-12-26 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statics', '0010_auto_20191226_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Checked Time')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checked_notifications', to='statics.Notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checked_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '알림 확인 여부',
                'verbose_name_plural': '알림 확인 여부',
                'ordering': ['-id'],
            },
        ),
    ]
