# Generated by Django 2.2.7 on 2019-12-31 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statics', '0011_notificationcheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='replies',
            field=models.ManyToManyField(blank=True, null=True, related_name='_reply_replies_+', to='statics.Reply'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='statics.Review'),
        ),
    ]
