# Generated by Django 2.2.7 on 2020-01-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statics', '0012_auto_20191231_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='review',
            name='expression',
            field=models.CharField(blank=True, choices=[('good', 'Good'), ('soso', 'Soso'), ('sad', 'Sad'), ('surprise', 'Surprise'), ('thumb', 'Thumb')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.FloatField(blank=True, null=True, verbose_name='평점'),
        ),
    ]
