# Generated by Django 2.2.7 on 2020-01-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statics', '0013_auto_20200114_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='index',
            field=models.PositiveIntegerField(default=1, verbose_name='순서'),
        ),
    ]
