# Generated by Django 2.2.7 on 2020-01-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statics', '0014_review_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='목록 삭제 여부'),
        ),
        migrations.AddField(
            model_name='review',
            name='reported',
            field=models.BooleanField(default=False, verbose_name='신고 여부'),
        ),
    ]
