# Generated by Django 2.2.7 on 2020-01-21 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statics', '0015_auto_20200121_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reported',
        ),
    ]
