# Generated by Django 2.2.7 on 2020-01-21 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statics', '0016_remove_review_reported'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statics.Review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '신고 목록',
                'verbose_name_plural': '신고 목록',
                'ordering': ['-id'],
            },
        ),
    ]
