# Generated by Django 2.2.7 on 2020-01-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statics', '0017_reporting'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='index',
            field=models.PositiveIntegerField(default=1, verbose_name='순서'),
        ),
    ]
