# Generated by Django 2.2.7 on 2020-01-26 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statics', '0019_auto_20200122_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='statics.Review', verbose_name='숨김당한 감상')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blockeds', to=settings.AUTH_USER_MODEL, verbose_name='숨김당한 유저')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockings', to=settings.AUTH_USER_MODEL, verbose_name='숨김한 유저')),
            ],
            options={
                'verbose_name': '숨김 목록',
                'verbose_name_plural': '숨김 목록',
                'ordering': ['-id'],
            },
        ),
    ]
