# Generated by Django 2.2.7 on 2020-01-26 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statics', '0020_blocking'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocking',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='statics.Reply', verbose_name='숨김당한 답변'),
        ),
        migrations.AddField(
            model_name='reporting',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='statics.Reply', verbose_name='신고당한 답변'),
        ),
    ]
