# Generated by Django 2.2.7 on 2020-01-26 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statics', '0020_auto_20200126_1444'),
        ('statics', '0022_reply_deleted'),
    ]

    operations = [
    ]
