# Generated by Django 2.2.7 on 2020-01-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_auto_20191220_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='index',
            field=models.PositiveIntegerField(default=1, verbose_name='순서'),
        ),
    ]
