# Generated by Django 2.2.7 on 2019-11-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='smkim', max_length=255, verbose_name='닉네임'),
            preserve_default=False,
        ),
    ]
