# Generated by Django 2.2.7 on 2019-12-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191208_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recommended',
            field=models.BooleanField(default=False, verbose_name='추천 여부'),
        ),
    ]
