# Generated by Django 2.2.7 on 2020-01-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20191212_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='initial',
            field=models.BooleanField(default=True, verbose_name='첫 사용 여부'),
        ),
        migrations.AddField(
            model_name='user',
            name='push_token',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='푸쉬 토큰'),
        ),
    ]
