# Generated by Django 2.2.7 on 2020-01-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeRedirectURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
            ],
            options={
                'verbose_name': '홈 Redirect URL',
                'verbose_name_plural': '홈 Redirect URL',
                'ordering': ['-id'],
            },
        ),
    ]
