# Generated by Django 2.2.7 on 2019-11-12 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artwork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='이름')),
                ('content', models.TextField(verbose_name='내용')),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('notopendate', models.DateField()),
                ('region', models.CharField(max_length=255, verbose_name='지역')),
                ('address', models.CharField(max_length=500, verbose_name='주소')),
                ('scale', models.FloatField()),
                ('fee', models.FloatField(verbose_name='요금')),
                ('artists', models.ManyToManyField(related_name='exhibitions', to='artwork.Artist')),
                ('artworks', models.ManyToManyField(related_name='exhibitions', to='artwork.Artwork')),
            ],
            options={
                'verbose_name': '전시',
                'verbose_name_plural': '전시',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='이름')),
                ('location', models.CharField(max_length=500, verbose_name='위치')),
            ],
            options={
                'verbose_name': '갤러리',
                'verbose_name_plural': '갤러리',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ExhibitionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='exhibition/image/')),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='exhibition.Exhibition')),
            ],
            options={
                'verbose_name': '전시 이미지',
                'verbose_name_plural': '전시 이미지',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='exhibition',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibitions', to='exhibition.Gallery'),
        ),
    ]
