# Generated by Django 2.2.7 on 2019-12-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='recommended',
            field=models.BooleanField(default=False, verbose_name='추천 여부'),
        ),
    ]
