# Generated by Django 2.2.7 on 2019-12-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0002_exhibition_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='scale',
            field=models.CharField(choices=[('large', '중대형'), ('small', '소형')], max_length=500, verbose_name='규모'),
        ),
    ]
