# Generated by Django 2.2.7 on 2019-12-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0003_auto_20191210_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='scale',
            field=models.CharField(choices=[('중대형', '중대형'), ('소형', '소형')], max_length=500, verbose_name='규모'),
        ),
    ]
