# Generated by Django 2.2.7 on 2019-12-19 16:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0005_auto_20191219_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='내용'),
        ),
    ]
