# Generated by Django 2.2.7 on 2020-01-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0007_auto_20191220_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='address',
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='region',
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='scale',
        ),
        migrations.AddField(
            model_name='gallery',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='주소'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='지역'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='scale',
            field=models.CharField(blank=True, choices=[('중대형', '중대형'), ('소형', '소형')], max_length=500, null=True, verbose_name='규모'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='website',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='웹 사이트'),
        ),
    ]
