# Generated by Django 2.2.7 on 2020-01-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0010_auto_20200115_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='index',
            field=models.PositiveIntegerField(default=1, verbose_name='순서'),
        ),
    ]
