# Generated by Django 2.2.7 on 2020-01-21 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exhibition', '0011_exhibition_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitionView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='exhibition.Exhibition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '전시 관람 여부',
                'verbose_name_plural': '전시 관람 여부',
                'ordering': ['-id'],
            },
        ),
    ]
